steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/qmobile-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/qmobile-backend:latest'
      - '.'
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/qmobile-backend:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qmobile-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/qmobile-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/qmobile-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/qmobile-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY